[[pages]]
path = "app.py"
name = "Inicio"
icon = "ğŸ "

# Pages after an `is_section = true` will be indented
[[pages]]
path = "pages/Tienda.py"
name = "Tienda"
icon = "ğŸ’„"

[[pages]]
path = "pages/FAQ.py"
name = "FAQ"
icon = "â“"

